version: '3.4'

networks:
  backend:
    driver: bridge

services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./services/backend/src:/var/www/html
    ports:
      - "8181:8000"
    networks:
      - backend

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
#      target: production-stage
    ports:
      - "9921:5173"
    volumes:
      - ./services/frontend/src:/app
    networks:
      - backend

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./services/database:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend